### ISSUE TITLE
No changes after upgrade to 0.5.0

### ISSUE THREAD

**Issue by chriskempson** [rsimmons/voracious#10]
Not seeing the 'Selected Text' option for Anki fields nor the 'Ignored Subtitle Languages' setting despite the app telling me I'm running version 0.5.0. I used the Windows installer and performed an upgrade. Also tried to uninstall and reinstall but no luck.

**Comment by rsimmons** [comment]
Oops, I will fix shortly.

**Comment by rsimmons** [comment]
I made a mistake in the build/release of just the Windows versions, so I have updated them without changing the version number. Please try again!

**Comment by chriskempson** [comment]
Perfect thanks!
