### ISSUE TITLE
Allow exit of fullscreen mode when in library/settings screens

### ISSUE THREAD

**Issue by chriskempson** [rsimmons/voracious#13]
When watching a video, press the `f` key for fullscreen mode, return the library or settings screens, the `f` key no longer responds meaning you're trapped in fullscreen mode. When this happens I have to start a video playing to escape fullscreen mode.

**Comment by rsimmons** [comment]
It's a bit tricky to make the `f` key work outside the player for fullscreen, so for now I've just made it exit fullscreen when you exit the video.
