### ISSUE TITLE
Deleting library videos leads to complete program failure

### ISSUE THREAD

**Issue by tscheney** [rsimmons/voracious#18]
I deleted some videos that were in the Voracious Library and the program was rendered completely inoperable, giving the following error on program start:

Something has gone terribly wrong

Error: ENOENT: no such file or directory, scandir '(my video path)'

Also, a panel on the right should have opened with more debug info. Maybe take a screenshot of everything and send it to me.

![error](https://user-images.githubusercontent.com/25555573/51444399-4e02ad00-1cb4-11e9-9c6e-148349f191b0.PNG)

In order to get it working again I had to go hunting for the preferences and ended up deleting both cookie files, as well as the preferences and voracious.db files in my appdata folder. A reinstall did not fix, because, I assume, whichever of those files that was causing the issue was still there.

**Comment by rsimmons** [comment]
Thanks for the report.
