### ISSUE TITLE
Chinese subtitles make player page crash

### ISSUE THREAD

**Issue by rsimmons** [rsimmons/voracious#27]
Andrew Cheung reported this to me by email. The subtitle language is correctly auto-determined as `cmn` (3-letter code), but the player page tries to convert this to a 2-letter code for the HTML `lang` attribute and fails because there is no conversion. It should just skip setting the attribute if the conversion fails.

**Comment by cmviall** [comment]
Hey @rsimmons we have similar backgrounds (nice to meet another person from a park). I'm a Stanford alum building a startup and want to ask you about common pitfalls given our experiences. Free for a 15 minute call this week? And apologies for the forum - feel free to email me chris@trysonal.com..
