### ISSUE TITLE
Export highlighted word to Anki

### ISSUE THREAD

**Issue by chriskempson** [rsimmons/voracious#3]
I study vocab in context with mined sentences but I find it far more useful having my cards point out the word I am learning. 

Words act as a unique field in my deck whereas the same sentence can exist multiple times. This setup ensures Yomichan wont import duplicate words and allows me to assign the highlighted word's glossary to card also.

**Comment by rsimmons** [comment]
This makes sense, I'll look into adding it in the next version. Thanks for the feedback.

**Comment by chriskempson** [comment]
Great! Once this is implemented and the [parsing adjusted](https://www.reddit.com/r/LearnJapanese/comments/9cyo94/voracious_a_video_player_for_learning_languages/e5t6z0x) I should be able to retire Yomichan for visual media based vocab/sentence mining 👍

**Comment by rsimmons** [comment]
This was added in 2734921 and just released in version 0.5.0.

**Comment by chriskempson** [comment]
Thanks 😄
