### ISSUE TITLE
Voracious can't be opened because of a problem 

### ISSUE THREAD

**Issue by callum-gander** [rsimmons/voracious#43]
Hi, 

The player won't open on mac at all, I'm getting the error below. Thanks

Process:               Voracious [31927]
Path:                  /Applications/Voracious.app/Contents/MacOS/Voracious
Identifier:            org.rsimmons.voracious
Version:               0.6.0 (0.6.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Voracious [31927]
User ID:               502

Date/Time:             2020-04-09 12:26:05.727 +0100
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Bridge OS Version:     4.1 (17P1081)
Anonymous UUID:        B4CBE627-E740-43F4-A906-AD5A394F9E18

Sleep/Wake UUID:       5A014613-727B-4A06-9FB8-70B0F07AAF7C

Time Awake Since Boot: 350000 seconds
Time Since Wake:       1900 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Voracious.app/Contents/MacOS/Voracious
  Reason: no suitable image found.  Did find:
	/Applications/Voracious.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Voracious.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10f7f1000 -        0x10f7f1ff7 +org.rsimmons.voracious (0.6.0 - 0.6.0) <5D51F11B-3CC9-3193-BD67-27427F5B22BA> /Applications/Voracious.app/Contents/MacOS/Voracious
       0x118202000 -        0x118292b5f  dyld (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770> /usr/lib/dyld
    0x7fff3d237000 -     0x7fff3d34fff8  com.apple.Bluetooth (7.0.1 - 7.0.1f1) <61A2BDF8-E3AC-3714-A967-92404AC52389> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

**Comment by rajlego** [comment]
I'm having the same error though I'm not sure how to get as many details

**Comment by chibigit** [comment]
Me too! Same error.

I googled "Framework.framework/Electron Framework: file too short" and found
https://github.com/electron-userland/electron-builder/issues/3674

which says "It appears that this only happens if the .zip file is extracted using The Unarchiver. If the built-in .zip extractor is used, things work properly. Looking at previous discussion on this it may have something to do with the use of symlinks/aliases within the set of files in the .app archive."

But I used the built in archive utility to unzip Voracious. :(

So perverse woman that I am, I tried opening the zip file with The Unarchiver and voila! It works. And it's fantastic!

**Comment by rajlego** [comment]
Wow, totally bizarre but unarchiver also worked for me! Thanks!

**Comment by clouedoc** [comment]
It works, thank you !

**Comment by artemmezh** [comment]
add to readme 
https://github.com/artemmezh/voracious/blob/test-0.7.1/README.md#cant-start-application-cause--file-too-short
