### ISSUE TITLE
How can I use it for English?

### ISSUE THREAD

**Issue by ghost** [rsimmons/voracious#44]
I have a mkv files which they has softsubs .ass formatted, also I have .srt but it doesn't show subtitles. Besides, I couldn't import english dictionary

**Comment by Bugallow** [comment]
You can extract the softsubs with mkvtoolnix. Make sure your srt file has the same name as the video and it's in the same folder. Also, the app can't open mkv videos currently, I use handbrake to convert them to mp4.

**Comment by ghost** [comment]
Thank you, I could not find english dict, Hope I will :)

**Comment by Bugallow** [comment]
Nah, unfortunately Voracious only supports EPWING (Japanese filetype). You won't be able to find dictionaries that don't somehow include Japanese.
