### ISSUE TITLE
Anki Connect Error because Origin in the request header is null

### ISSUE THREAD

**Issue by xiaomi388** [rsimmons/voracious#61]
Hi, when I tried to connect the app with Anki, I got this error:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/14134844/161299633-4df3560d-5416-4be6-bf2c-9e533040c067.png">

I captured the HTTP packets and found out that ankiconnect returned 403. Seems like it was because the request contained a null origin:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/14134844/161299942-8f85cbf0-1a22-4127-bd90-50d0b42b590a.png">

It worked well after I removed the Origin header by using some kind of MITM hack, but I would greatly appreciate it if someone could fix this issue ;)

**Comment by artemmezh** [comment]
Hi! You can fix it by adding * to config for ankiConnect ads.
Please check my fork, i created description https://github.com/artemmezh/voracious/blob/ankiConnect-fix-new-version/README.md#about-ankiconnect
