### ISSUE TITLE
AnkiConnect Status: Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Calm99999** [rsimmons/voracious#64]
I can't make Anki cards=(

**Comment by Calm99999** [comment]
And I have Anki Connect. I use 0.6.0 version of Voracious

**Comment by jonstrutz11** [comment]
https://www.reddit.com/r/Anki/comments/n8kcx1/comment/i0l6p8z/?utm_source=share&utm_medium=web2x&context=3
solved it for me @Calm99999
