### ISSUE TITLE
Hide subtitles for specific languages

### ISSUE THREAD

**Issue by chriskempson** [rsimmons/voracious#7]
I removed 'eng' from the 'Subtitle Language Order' settings field hoping it would prevent English subtitles from being displayed but sadly not 😢 

Might be nice if there was some way of choosing which languages are displayed? For the time being I'm just hiding English subs in a sub-directory.

**Comment by rsimmons** [comment]
I think it would make sense to have another setting for 'Ignored Subtitle Languages', a list of language codes that are just ignored. I can add that to the list for the next release.

**Comment by rsimmons** [comment]
This has now been released in 0.5.0.

**Comment by chriskempson** [comment]
Thanks, works great!
