### ISSUE TITLE
AppImage crash on Linux

### ISSUE THREAD

**Issue by baongoc124** [rsimmons/voracious#8]
It just crashed when I tried to run it for the first time. How could I provide more debug info?

**Comment by rsimmons** [comment]
Thanks for the report. What distribution/version are you running? Did it show a window before it crashed? Also, do you know if you're successfully running any other Electron-based apps? (e.g. Slack)

**Comment by baongoc124** [comment]
Thanks for your prompt reply.
I'm running it on Archlinux (rolling release it is). No window had shown before it crashed. It only displayed this message "Segmentation fault (core dumped)".
Slack works fine on my machine.

**Comment by rsimmons** [comment]
I suspect that this is due to a bug in Electron (https://github.com/electron/electron/issues/13972). I'll update Voracious to use a fixed version of Electron in an upcoming release, and once that's out I'll check with you that it's fixed.

**Comment by rsimmons** [comment]
This should be fixed by a6167ca, which is in the new 0.5.0 release if you want to try it out. Let me know if it isn't fixed.

**Comment by baongoc124** [comment]
It's fixed. Many thanks!
