### ISSUE TITLE
Some Subtitles Do Not Display

### ISSUE THREAD

**Issue by tscheney** [rsimmons/voracious#9]
Not sure if this is my issue or not, but the attached subtitles do not display. I saw you mention on reddit that it expects UTF-8, so I tried exporting the file as UTF-8 in AegisSub and then re-muxing with MKVToolNix, but the subtitles still do not show. This is the only one I've tried so far, so I'm not entirely sure if there is something I'm missing here.
[subs.zip](https://github.com/rsimmons/voracious/files/2426905/subs.zip)

**Comment by rsimmons** [comment]
Voracious expects subs to be in a separate file with the same name as the video. It doesn't support muxed subs. This might not be clear from the documentation, sorry. I tested those subs in a separate file and they work fine. Let me know if that works for you.

**Comment by tscheney** [comment]
Yes, I didn't realize it didn't support embedded subs. It's working fine with the separate subtitle file. Thanks for your help.
